import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting database seeding...');
  console.log('📦 Clearing existing products...');

  // Clear existing products safely
  await prisma.product.deleteMany({});

  console.log('✅ Existing products cleared');
  console.log('👤 Creating default vendor account...\n');

  const vendorUser = await prisma.user.create({
    data: {
      name: 'Default Vendor',
      email: 'vendor@vibebasket.local',
      password: 'vendor-password',
      role: 'vendor',
    },
  });

  const vendor = await prisma.vendor.create({
    data: {
      userId: vendorUser.id,
      status: 'APPROVED',
      commissionRate: 12,
      payoutBalance: 0,
      verified: true,
    },
  });

  console.log('📦 Creating 100 new products...\n');

  // ============================================
  // CLOTHING - MEN'S (15 products)
  // ============================================
  const mensClothing = [
    {
      title: 'Classic Oxford Shirt - White',
      description: 'Premium cotton oxford shirt perfect for office and formal occasions. Crisp, clean and confidence-boosting.',
      category: 'clothing',
      price: 49.99,
      stock: 150,
      tags: ['casual', 'office', 'premium', 'confidence', 'formal'],
      image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf',
      inStock: true,
      vendorId: vendor.id,
    },
    {
      title: 'Slim Fit Navy Blazer',
      description: 'Tailored navy blazer for the modern professional. Elegant and versatile for meetings and parties.',
      category: 'clothing',
      price: 149.99,
      stock: 80,
      tags: ['elegant', 'office', 'premium', 'party', 'confidence', 'slim-fit'],
      image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf',
      inStock: true,
      vendorId: vendor.id,
    },
    {
      title: 'Relaxed Fit Denim Jeans',
      description: 'Comfortable everyday jeans with a relaxed fit. Perfect for casual outings and daily wear.',
      category: 'clothing',
      price: 69.99,
      stock: 200,
      tags: ['casual', 'daily-use', 'comfort', 'relaxed-fit', 'budget'],
      image: 'https://images.unsplash.com/photo-1542272604-787c3835535d',
      inStock: true,
      vendorId: vendor.id,
    },
    {
      title: 'Merino Wool Sweater - Charcoal',
      description: 'Luxuriously soft merino wool sweater. Ideal for romantic dinners and winter occasions.',
      category: 'clothing',
      price: 89.99,
      stock: 120,
      tags: ['premium', 'comfort', 'romantic', 'elegant', 'winter'],
      image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27',
      inStock: true,
      vendorId: vendor.id,
    },
    {
      title: 'Performance Track Pants',
      description: 'Athletic track pants with moisture-wicking fabric. Built for gym, running and active lifestyle.',
      category: 'clothing',
      price: 44.99,
      stock: 180,
      tags: ['sporty', 'performance', 'gym', 'daily-use', 'comfort'],
      image: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8',
      inStock: true,
      vendorId: vendor.id,
    },
    {
      title: 'Graphic Print T-Shirt - Black',
      description: 'Trendy graphic tee for college and casual hangouts. Comfortable cotton blend.',
      category: 'clothing',
      price: 24.99,
      stock: 250,
      tags: ['casual', 'college', 'trendy', 'budget', 'daily-use'],
      image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab',
      inStock: true,
      vendorId: vendor.id,
    },
    {
      title: 'Premium Leather Jacket - Brown',
      description: 'Classic leather jacket that exudes confidence and style. Perfect for dates and parties.',
      category: 'clothing',
      price: 299.99,
      stock: 50,
      tags: ['premium', 'leather', 'party', 'romantic', 'confidence', 'trendy'],
      image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5',
      inStock: true,
      vendorId: vendor.id,
    },
    {
      title: 'Linen Summer Shirt - Sky Blue',
      description: 'Breathable linen shirt for hot summer days. Lightweight and comfortable for travel.',
      category: 'clothing',
      price: 54.99,
      stock: 140,
      tags: ['casual', 'comfort', 'travel', 'lightweight', 'summer'],
      image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c',
      inStock: true,
      vendorId: vendor.id,
    },
    {
      title: 'Tailored Dress Pants - Grey',
      description: 'Professional dress pants with a modern cut. Essential for office and formal events.',
      category: 'clothing',
      price: 79.99,
      stock: 130,
      tags: ['office', 'formal', 'elegant', 'confidence', 'slim-fit'],
      image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a',
      inStock: true,
      vendorId: vendor.id,
    },
    {
      title: 'Hooded Sweatshirt - Heather Grey',
      description: 'Cozy hoodie for relaxed days. Perfect for college, gym warmups, or lazy weekends.',
      category: 'clothing',
      price: 39.99,
      stock: 220,
      tags: ['casual', 'comfort', 'college', 'budget', 'daily-use', 'relaxed-fit'],
      image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7',
      inStock: true,
      vendorId: vendor.id,
    },
    {
      title: 'Compression Workout Shirt',
      description: 'High-performance compression shirt for intense workouts. Enhances athletic performance.',
      category: 'clothing',
      price: 34.99,
      stock: 160,
      tags: ['sporty', 'performance', 'gym', 'athletic', 'slim-fit'],
      image: 'https://images.unsplash.com/photo-1571731956672-f2b94d7dd0cb',
      inStock: true,
      vendorId: vendor.id,
    },
    {
      title: 'Polo Shirt - Navy Stripe',
      description: 'Classic polo shirt for smart-casual occasions. Versatile for office casual and outings.',
      category: 'clothing',
      price: 44.99,
      stock: 170,
      tags: ['casual', 'office', 'comfort', 'daily-use'],
      image: 'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d',
      inStock: true,
      vendorId: vendor.id,
    },
    {
      title: 'Winter Parka Jacket - Olive',
      description: 'Insulated parka for harsh winters. Durable, warm and functional for outdoor adventures.',
      category: 'clothing',
      price: 179.99,
      stock: 90,
      tags: ['winter', 'durability', 'travel', 'outdoor', 'comfort'],
      image: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a',
      inStock: true,
      vendorId: vendor.id,
    },
    {
      title: 'Chino Shorts - Khaki',
      description: 'Comfortable chino shorts for summer. Perfect for casual outings and travel.',
      category: 'clothing',
      price: 42.99,
      stock: 190,
      tags: ['casual', 'summer', 'travel', 'comfort', 'budget'],
      image: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b',
      inStock: true,
      vendorId: vendor.id,
    },
    {
      title: 'V-Neck Cotton Tee - White',
      description: 'Essential white v-neck t-shirt. A wardrobe staple for daily wear and layering.',
      category: 'clothing',
      price: 19.99,
      stock: 300,
      tags: ['casual', 'daily-use', 'budget', 'comfort', 'basic'],
      image: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820',
      inStock: true,
      vendorId: vendor.id,
    },
  ];

  // ============================================
  // CLOTHING - WOMEN'S (15 products)
  // ============================================
  const womensClothing = [
    {
      title: 'Elegant Midi Dress - Black',
      description: 'Timeless black midi dress perfect for romantic dates, parties, and special occasions.',
      category: 'clothing',
      price: 89.99,
      stock: 120,
      tags: ['elegant', 'romantic', 'party', 'premium', 'confidence'],
      image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8',
      inStock: true,
      vendorId: vendor.id,
    },
    {
      title: 'Silk Blouse - Ivory',
      description: 'Luxurious silk blouse for the office and elegant events. Sophisticated and polished.',
      category: 'clothing',
      price: 79.99,
      stock: 100,
      tags: ['elegant', 'office', 'premium', 'confidence', 'sophisticated'],
      image: 'https://images.unsplash.com/photo-1564859228273-274232fdb516',
      inStock: true,
    },
    {
      title: 'High-Waisted Skinny Jeans',
      description: 'Figure-flattering skinny jeans for daily wear. Comfortable stretch denim.',
      category: 'clothing',
      price: 64.99,
      stock: 180,
      tags: ['casual', 'daily-use', 'comfort', 'trendy', 'slim-fit'],
      image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246',
      inStock: true,
    },
    {
      title: 'Cashmere Cardigan - Beige',
      description: 'Soft cashmere cardigan for cozy evenings. Perfect for romantic occasions and comfort.',
      category: 'clothing',
      price: 129.99,
      stock: 90,
      tags: ['premium', 'comfort', 'romantic', 'elegant', 'luxury'],
      image: 'https://images.unsplash.com/photo-1591369822096-ffd140ec948f',
      inStock: true,
    },
    {
      title: 'Athletic Leggings - Black',
      description: 'High-performance leggings for yoga, gym, and running. Moisture-wicking and supportive.',
      category: 'clothing',
      price: 49.99,
      stock: 200,
      tags: ['sporty', 'performance', 'gym', 'comfort', 'athletic'],
      image: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8',
      inStock: true,
    },
    {
      title: 'Floral Print Maxi Dress',
      description: 'Beautiful floral maxi dress for summer parties and romantic occasions.',
      category: 'clothing',
      price: 94.99,
      stock: 110,
      tags: ['romantic', 'party', 'summer', 'trendy', 'elegant'],
      image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1',
      inStock: true,
    },
    {
      title: 'Oversized Knit Sweater - Cream',
      description: 'Cozy oversized sweater perfect for relaxed weekends and college days.',
      category: 'clothing',
      price: 59.99,
      stock: 150,
      tags: ['casual', 'comfort', 'college', 'relaxed-fit', 'cozy'],
      image: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105',
      inStock: true,
    },
    {
      title: 'Tailored Blazer - Burgundy',
      description: 'Sophisticated blazer for professional settings. Adds confidence to any outfit.',
      category: 'clothing',
      price: 139.99,
      stock: 85,
      tags: ['office', 'elegant', 'premium', 'confidence', 'formal'],
      image: 'https://images.unsplash.com/photo-1591369822096-ffd140ec948f',
      inStock: true,
    },
    {
      title: 'Denim Jacket - Light Wash',
      description: 'Classic denim jacket for casual outings. Versatile layering piece for any season.',
      category: 'clothing',
      price: 69.99,
      stock: 140,
      tags: ['casual', 'trendy', 'daily-use', 'versatile'],
      image: 'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3',
      inStock: true,
    },
    {
      title: 'Sports Bra - Rose Pink',
      description: 'Supportive sports bra for high-impact workouts. Comfortable and performance-focused.',
      category: 'clothing',
      price: 34.99,
      stock: 190,
      tags: ['sporty', 'gym', 'performance', 'comfort', 'athletic'],
      image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b',
      inStock: true,
    },
    {
      title: 'Pleated Midi Skirt - Navy',
      description: 'Elegant pleated skirt for office and formal events. Timeless and sophisticated.',
      category: 'clothing',
      price: 54.99,
      stock: 130,
      tags: ['office', 'elegant', 'formal', 'sophisticated'],
      image: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa',
      inStock: true,
    },
    {
      title: 'Cotton T-Shirt Dress - Grey',
      description: 'Comfortable t-shirt dress for everyday wear. Easy, casual, and effortless.',
      category: 'clothing',
      price: 39.99,
      stock: 170,
      tags: ['casual', 'comfort', 'daily-use', 'budget', 'relaxed-fit'],
      image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1',
      inStock: true,
    },
    {
      title: 'Trench Coat - Classic Beige',
      description: 'Iconic trench coat for rainy days and elegant outings. Timeless fashion staple.',
      category: 'clothing',
      price: 189.99,
      stock: 70,
      tags: ['elegant', 'premium', 'travel', 'sophisticated', 'classic'],
      image: 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3',
      inStock: true,
    },
    {
      title: 'Crop Top - White Ribbed',
      description: 'Trendy crop top for summer and casual occasions. Pairs perfectly with high-waisted bottoms.',
      category: 'clothing',
      price: 24.99,
      stock: 210,
      tags: ['trendy', 'casual', 'summer', 'budget', 'college'],
      image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1',
      inStock: true,
    },
    {
      title: 'Yoga Tank Top - Mint Green',
      description: 'Breathable tank top for yoga and pilates. Lightweight and moisture-wicking.',
      category: 'clothing',
      price: 29.99,
      stock: 180,
      tags: ['sporty', 'gym', 'comfort', 'lightweight', 'athletic'],
      image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7',
      inStock: true,
    },
  ];

  // ============================================
  // FOOTWEAR (15 products)
  // ============================================
  const footwear = [
    {
      title: 'Running Shoes - Performance Pro',
      description: 'Professional running shoes with advanced cushioning. Built for speed and endurance.',
      category: 'footwear',
      price: 129.99,
      stock: 150,
      tags: ['sporty', 'running', 'performance', 'athletic', 'comfort'],
      image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff',
      inStock: true,
    },
    {
      title: 'Classic Leather Dress Shoes - Black',
      description: 'Timeless leather dress shoes for office and formal occasions. Polished and professional.',
      category: 'footwear',
      price: 149.99,
      stock: 100,
      tags: ['office', 'formal', 'premium', 'leather', 'elegant', 'confidence'],
      image: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509',
      inStock: true,
    },
    {
      title: 'White Sneakers - Minimalist',
      description: 'Clean white sneakers for everyday wear. Versatile and comfortable for all occasions.',
      category: 'footwear',
      price: 79.99,
      stock: 220,
      tags: ['casual', 'daily-use', 'comfort', 'trendy', 'college'],
      image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772',
      inStock: true,
    },
    {
      title: 'Hiking Boots - All-Terrain',
      description: 'Durable hiking boots for outdoor adventures. Waterproof and supportive for trails.',
      category: 'footwear',
      price: 159.99,
      stock: 90,
      tags: ['outdoor', 'durability', 'travel', 'adventure', 'comfort'],
      image: 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0',
      inStock: true,
    },
    {
      title: 'Ballet Flats - Nude',
      description: 'Elegant ballet flats for office and casual wear. Comfortable all-day footwear.',
      category: 'footwear',
      price: 64.99,
      stock: 140,
      tags: ['office', 'casual', 'comfort', 'elegant', 'daily-use'],
      image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2',
      inStock: true,
    },
    {
      title: 'High-Top Basketball Shoes',
      description: 'Performance basketball shoes with ankle support. Designed for court dominance.',
      category: 'footwear',
      price: 139.99,
      stock: 110,
      tags: ['sporty', 'basketball', 'performance', 'athletic', 'gym'],
      image: 'https://images.unsplash.com/photo-1600269452121-4f2416e55c28',
      inStock: true,
    },
    {
      title: 'Chelsea Boots - Brown Suede',
      description: 'Stylish chelsea boots for smart-casual and romantic occasions. Classic and versatile.',
      category: 'footwear',
      price: 129.99,
      stock: 95,
      tags: ['casual', 'romantic', 'trendy', 'premium', 'confidence'],
      image: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f',
      inStock: true,
    },
    {
      title: 'Slip-On Loafers - Navy',
      description: 'Comfortable loafers for office and travel. Easy to wear and always stylish.',
      category: 'footwear',
      price: 89.99,
      stock: 130,
      tags: ['office', 'travel', 'comfort', 'casual', 'convenience'],
      image: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4',
      inStock: true,
    },
    {
      title: 'Sandals - Summer Slide',
      description: 'Lightweight sandals for hot summer days. Perfect for beach and casual outings.',
      category: 'footwear',
      price: 34.99,
      stock: 200,
      tags: ['summer', 'casual', 'lightweight', 'comfort', 'budget'],
      image: 'https://images.unsplash.com/photo-1603487742131-4160ec999306',
      inStock: true,
    },
    {
      title: 'Pumps - Classic Black Heels',
      description: 'Elegant black pumps for formal events and parties. Confidence in every step.',
      category: 'footwear',
      price: 99.99,
      stock: 85,
      tags: ['formal', 'party', 'elegant', 'premium', 'confidence'],
      image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2',
      inStock: true,
    },
    {
      title: 'Canvas Sneakers - Red',
      description: 'Classic canvas sneakers for college and casual wear. Fun and comfortable.',
      category: 'footwear',
      price: 44.99,
      stock: 180,
      tags: ['casual', 'college', 'trendy', 'budget', 'comfort'],
      image: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77',
      inStock: true,
    },
    {
      title: 'Cross-Training Shoes',
      description: 'Versatile training shoes for gym workouts. Support for all fitness activities.',
      category: 'footwear',
      price: 94.99,
      stock: 160,
      tags: ['sporty', 'gym', 'performance', 'athletic', 'versatile'],
      image: 'https://images.unsplash.com/photo-1579338559194-a162d19bf842',
      inStock: true,
    },
    {
      title: 'Ankle Boots - Black Leather',
      description: 'Trendy ankle boots for fall and winter. Perfect for dates and parties.',
      category: 'footwear',
      price: 119.99,
      stock: 105,
      tags: ['trendy', 'romantic', 'party', 'premium', 'leather'],
      image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2',
      inStock: true,
    },
    {
      title: 'Boat Shoes - Tan',
      description: 'Casual boat shoes for summer and travel. Comfortable and water-resistant.',
      category: 'footwear',
      price: 74.99,
      stock: 125,
      tags: ['casual', 'summer', 'travel', 'comfort', 'water'],
      image: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86',
      inStock: true,
    },
    {
      title: 'Flip Flops - Beach Style',
      description: 'Simple flip flops for beach and pool. Lightweight and affordable.',
      category: 'footwear',
      price: 19.99,
      stock: 300,
      tags: ['summer', 'beach', 'budget', 'lightweight', 'casual'],
      image: 'https://images.unsplash.com/photo-1603487742131-4160ec999306',
      inStock: true,
    },
  ];

  // ============================================
  // ELECTRONICS (20 products)
  // ============================================
  const electronics = [
    {
      title: 'Noise-Canceling Wireless Headphones',
      description: 'Premium headphones with active noise cancellation. Perfect for travel and focus.',
      category: 'electronics',
      price: 299.99,
      stock: 120,
      tags: ['premium', 'tech', 'travel', 'music', 'focus'],
      image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e',
      inStock: true,
    },
    {
      title: 'Smart Watch - Fitness Tracker Pro',
      description: 'Advanced smartwatch with health monitoring. Track fitness goals and stay connected.',
      category: 'electronics',
      price: 249.99,
      stock: 150,
      tags: ['tech', 'fitness', 'sporty', 'health', 'smart'],
      image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30',
      inStock: true,
    },
    {
      title: 'Wireless Earbuds - True Sound',
      description: 'Compact wireless earbuds with crystal-clear audio. Great for gym and commuting.',
      category: 'electronics',
      price: 129.99,
      stock: 200,
      tags: ['tech', 'portable', 'gym', 'music', 'budget'],
      image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df',
      inStock: true,
    },
    {
      title: 'Portable Bluetooth Speaker',
      description: 'Waterproof speaker for parties and outdoor adventures. Powerful sound, portable size.',
      category: 'electronics',
      price: 89.99,
      stock: 170,
      tags: ['party', 'outdoor', 'portable', 'music', 'fun'],
      image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1',
      inStock: true,
    },
    {
      title: 'E-Reader - Digital Book Library',
      description: 'Lightweight e-reader for book lovers. Carry thousands of books everywhere.',
      category: 'electronics',
      price: 139.99,
      stock: 100,
      tags: ['reading', 'portable', 'travel', 'thoughtful', 'gift'],
      image: 'https://images.unsplash.com/photo-1589998059171-988d887df646',
      inStock: true,
    },
    {
      title: 'Smartphone Gimbal Stabilizer',
      description: 'Professional gimbal for smooth video recording. Perfect for content creators.',
      category: 'electronics',
      price: 149.99,
      stock: 85,
      tags: ['tech', 'creative', 'video', 'professional'],
      image: 'https://images.unsplash.com/photo-1519558260268-cde7e03a0152',
      inStock: true,
    },
    {
      title: 'Wireless Charging Pad',
      description: 'Fast wireless charger for smartphones. Convenient and cable-free charging.',
      category: 'electronics',
      price: 34.99,
      stock: 250,
      tags: ['tech', 'convenience', 'daily-use', 'budget'],
      image: 'https://images.unsplash.com/photo-1591290619762-d6229b0f7b8c',
      inStock: true,
    },
    {
      title: 'Gaming Mouse - RGB Pro',
      description: 'High-precision gaming mouse with customizable RGB. Built for competitive gaming.',
      category: 'electronics',
      price: 69.99,
      stock: 140,
      tags: ['gaming', 'tech', 'performance', 'fun'],
      image: 'https://images.unsplash.com/photo-1527814050087-3793815479db',
      inStock: true,
    },
    {
      title: 'Mechanical Keyboard - Tactile',
      description: 'Premium mechanical keyboard for typing and gaming. Satisfying tactile feedback.',
      category: 'electronics',
      price: 119.99,
      stock: 110,
      tags: ['tech', 'gaming', 'office', 'premium', 'productivity'],
      image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3',
      inStock: true,
    },
    {
      title: 'USB-C Hub - 7-in-1',
      description: 'Versatile USB-C hub with multiple ports. Essential for laptops and productivity.',
      category: 'electronics',
      price: 49.99,
      stock: 180,
      tags: ['tech', 'office', 'productivity', 'portability', 'convenience'],
      image: 'https://images.unsplash.com/photo-1625948515291-69613efd103f',
      inStock: true,
    },
    {
      title: 'External SSD - 1TB',
      description: 'Fast external SSD for file storage and backups. Portable and durable.',
      category: 'electronics',
      price: 139.99,
      stock: 130,
      tags: ['tech', 'storage', 'durability', 'portable', 'professional'],
      image: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b',
      inStock: true,
    },
    {
      title: 'Webcam - HD 1080p',
      description: 'High-definition webcam for video calls and streaming. Clear image quality.',
      category: 'electronics',
      price: 79.99,
      stock: 150,
      tags: ['tech', 'office', 'remote', 'productivity'],
      image: 'https://images.unsplash.com/photo-1622291304061-ec2f6d3a1e29',
      inStock: true,
    },
    {
      title: 'Portable Power Bank - 20000mAh',
      description: 'High-capacity power bank for travel. Charge multiple devices on the go.',
      category: 'electronics',
      price: 44.99,
      stock: 220,
      tags: ['travel', 'portable', 'convenience', 'tech', 'budget'],
      image: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5',
      inStock: true,
    },
    {
      title: 'Smart LED Light Bulb - Color',
      description: 'WiFi-enabled color-changing light bulb. Set the mood with smart lighting.',
      category: 'electronics',
      price: 29.99,
      stock: 200,
      tags: ['smart', 'home', 'mood', 'tech', 'budget'],
      image: 'https://images.unsplash.com/photo-1550985616-10810253b84d',
      inStock: true,
    },
    {
      title: 'Tablet Stand - Adjustable',
      description: 'Ergonomic tablet stand for desk work. Adjustable angles for comfort.',
      category: 'electronics',
      price: 24.99,
      stock: 160,
      tags: ['office', 'comfort', 'productivity', 'budget'],
      image: 'https://images.unsplash.com/photo-1631634961150-5e87a64b8e0c',
      inStock: true,
    },
    {
      title: 'Action Camera - 4K',
      description: 'Rugged 4K action camera for adventure recording. Waterproof and shockproof.',
      category: 'electronics',
      price: 199.99,
      stock: 75,
      tags: ['adventure', 'outdoor', 'tech', 'durability', 'video'],
      image: 'https://images.unsplash.com/photo-1519558260268-cde7e03a0152',
      inStock: true,
    },
    {
      title: 'Phone Case - Rugged Protection',
      description: 'Military-grade phone case with drop protection. Keep your phone safe.',
      category: 'electronics',
      price: 34.99,
      stock: 240,
      tags: ['protection', 'durability', 'daily-use', 'budget'],
      image: 'https://images.unsplash.com/photo-1585060544812-6b45742d762f',
      inStock: true,
    },
    {
      title: 'Desk Lamp - LED with USB',
      description: 'Modern LED desk lamp with USB charging port. Perfect for study and work.',
      category: 'electronics',
      price: 39.99,
      stock: 145,
      tags: ['office', 'study', 'convenience', 'budget'],
      image: 'https://images.unsplash.com/photo-1541140532154-b024d705b90a',
      inStock: true,
    },
    {
      title: 'Laptop Cooling Pad',
      description: 'Cooling pad with dual fans for laptops. Prevent overheating during intensive use.',
      category: 'electronics',
      price: 29.99,
      stock: 170,
      tags: ['tech', 'gaming', 'productivity', 'cooling', 'budget'],
      image: 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5',
      inStock: true,
    },
    {
      title: 'Smart Doorbell Camera',
      description: 'WiFi doorbell with HD video and motion detection. Enhance home security.',
      category: 'electronics',
      price: 149.99,
      stock: 90,
      tags: ['smart', 'home', 'security', 'tech'],
      image: 'https://images.unsplash.com/photo-1558002038-1055907df827',
      inStock: true,
    },
  ];

  // ============================================
  // LAPTOPS (10 products)
  // ============================================
  const laptops = [
    {
      title: 'UltraBook Pro - 13 inch',
      description: 'Lightweight ultrabook for professionals. Powerful performance in a portable design.',
      category: 'laptops',
      price: 1299.99,
      stock: 50,
      tags: ['premium', 'office', 'portable', 'professional', 'lightweight'],
      image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853',
      inStock: true,
    },
    {
      title: 'Gaming Laptop - RTX Edition',
      description: 'High-performance gaming laptop with dedicated graphics. Dominate every game.',
      category: 'laptops',
      price: 1799.99,
      stock: 40,
      tags: ['gaming', 'performance', 'premium', 'tech', 'powerful'],
      image: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302',
      inStock: true,
    },
    {
      title: 'Budget Chromebook - Student Edition',
      description: 'Affordable Chromebook perfect for students and basic tasks. Long battery life.',
      category: 'laptops',
      price: 299.99,
      stock: 80,
      tags: ['budget', 'student', 'college', 'portable', 'basic'],
      image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed',
      inStock: true,
    },
    {
      title: 'Creator Laptop - 4K Display',
      description: 'Laptop for creators with stunning 4K display. Perfect for photo and video editing.',
      category: 'laptops',
      price: 1999.99,
      stock: 35,
      tags: ['premium', 'creative', 'professional', 'performance', 'display'],
      image: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2',
      inStock: true,
    },
    {
      title: 'Business Laptop - Enterprise',
      description: 'Reliable business laptop with security features. Built for corporate professionals.',
      category: 'laptops',
      price: 1499.99,
      stock: 60,
      tags: ['office', 'professional', 'premium', 'durability', 'security'],
      image: 'https://images.unsplash.com/photo-1588702547923-7093a6c3ba33',
      inStock: true,
    },
    {
      title: '2-in-1 Convertible Laptop',
      description: 'Versatile 2-in-1 laptop with touchscreen. Laptop and tablet in one device.',
      category: 'laptops',
      price: 899.99,
      stock: 70,
      tags: ['versatile', 'portable', 'touchscreen', 'creative'],
      image: 'https://images.unsplash.com/photo-1527698266440-12104e498b76',
      inStock: true,
    },
    {
      title: 'MacBook Air Alternative',
      description: 'Sleek and thin laptop similar to MacBook Air. Great for everyday computing.',
      category: 'laptops',
      price: 1099.99,
      stock: 55,
      tags: ['premium', 'lightweight', 'portable', 'elegant', 'college'],
      image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8',
      inStock: true,
    },
    {
      title: 'Student Laptop - 15 inch',
      description: 'Affordable 15-inch laptop for students. Perfect balance of performance and price.',
      category: 'laptops',
      price: 549.99,
      stock: 100,
      tags: ['budget', 'student', 'college', 'daily-use', 'study'],
      image: 'https://images.unsplash.com/photo-1484788984921-03950022c9ef',
      inStock: true,
    },
    {
      title: 'Workstation Laptop - 17 inch',
      description: 'Powerful 17-inch workstation for engineers and developers. Maximum performance.',
      category: 'laptops',
      price: 2499.99,
      stock: 25,
      tags: ['professional', 'performance', 'premium', 'powerful', 'developer'],
      image: 'https://images.unsplash.com/photo-1593642702821-c8da6771f0c6',
      inStock: true,
    },
    {
      title: 'Refurbished Laptop - Certified',
      description: 'Quality refurbished laptop with warranty. Great value for budget-conscious buyers.',
      category: 'laptops',
      price: 399.99,
      stock: 90,
      tags: ['budget', 'value', 'daily-use', 'basic', 'affordable'],
      image: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1',
      inStock: true,
    },
  ];

  // ============================================
  // ACCESSORIES (15 products)
  // ============================================
  const accessories = [
    {
      title: 'Leather Wallet - Bifold',
      description: 'Classic leather bifold wallet. Slim design with RFID protection.',
      category: 'accessories',
      price: 49.99,
      stock: 180,
      tags: ['leather', 'premium', 'daily-use', 'gift', 'classic'],
      image: 'https://images.unsplash.com/photo-1627123424574-724758594e93',
      inStock: true,
    },
    {
      title: 'Polarized Sunglasses - Aviator',
      description: 'Classic aviator sunglasses with UV protection. Stylish and protective.',
      category: 'accessories',
      price: 89.99,
      stock: 140,
      tags: ['trendy', 'summer', 'travel', 'premium', 'style'],
      image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f',
      inStock: true,
    },
    {
      title: 'Laptop Backpack - Travel Pro',
      description: 'Durable backpack with laptop compartment. Perfect for travel and daily commute.',
      category: 'accessories',
      price: 79.99,
      stock: 160,
      tags: ['travel', 'office', 'durability', 'portable', 'daily-use'],
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62',
      inStock: true,
    },
    {
      title: 'Silk Tie - Navy with Pattern',
      description: 'Elegant silk tie for formal occasions. Adds sophistication to any suit.',
      category: 'accessories',
      price: 34.99,
      stock: 120,
      tags: ['formal', 'office', 'elegant', 'premium', 'gift'],
      image: 'https://images.unsplash.com/photo-1557804506-669a67965ba0',
      inStock: true,
    },
    {
      title: 'Watch - Minimalist Design',
      description: 'Sleek minimalist watch with leather strap. Timeless elegance for any occasion.',
      category: 'accessories',
      price: 149.99,
      stock: 95,
      tags: ['elegant', 'premium', 'gift', 'classic', 'sophisticated'],
      image: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d',
      inStock: true,
    },
    {
      title: 'Crossbody Bag - Canvas',
      description: 'Casual canvas crossbody bag for everyday use. Practical and stylish.',
      category: 'accessories',
      price: 44.99,
      stock: 150,
      tags: ['casual', 'daily-use', 'travel', 'budget', 'practical'],
      image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa',
      inStock: true,
    },
    {
      title: 'Leather Belt - Brown',
      description: 'Quality leather belt for dress pants. Durable and timeless.',
      category: 'accessories',
      price: 39.99,
      stock: 200,
      tags: ['leather', 'office', 'formal', 'classic', 'durability'],
      image: 'https://images.unsplash.com/photo-1624222247344-70f1f3fd21e4',
      inStock: true,
    },
    {
      title: 'Scarf - Wool Blend',
      description: 'Cozy wool blend scarf for cold weather. Adds warmth and style.',
      category: 'accessories',
      price: 29.99,
      stock: 170,
      tags: ['winter', 'comfort', 'casual', 'gift', 'cozy'],
      image: 'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9',
      inStock: true,
    },
    {
      title: 'Baseball Cap - Cotton',
      description: 'Classic cotton baseball cap for casual wear. Comfortable and versatile.',
      category: 'accessories',
      price: 24.99,
      stock: 220,
      tags: ['casual', 'sporty', 'summer', 'budget', 'daily-use'],
      image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b',
      inStock: true,
    },
    {
      title: 'Tote Bag - Eco-Friendly',
      description: 'Sustainable canvas tote bag for shopping and daily use. Environmentally conscious.',
      category: 'accessories',
      price: 19.99,
      stock: 250,
      tags: ['eco', 'daily-use', 'budget', 'practical', 'casual'],
      image: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7',
      inStock: true,
    },
    {
      title: 'Beanie - Knit',
      description: 'Warm knit beanie for winter. Cozy and comfortable head warmth.',
      category: 'accessories',
      price: 19.99,
      stock: 190,
      tags: ['winter', 'comfort', 'casual', 'budget', 'cozy'],
      image: 'https://images.unsplash.com/photo-1576871337622-98d48d1cf531',
      inStock: true,
    },
    {
      title: 'Travel Toiletry Bag',
      description: 'Waterproof toiletry bag for travel. Organized and convenient.',
      category: 'accessories',
      price: 29.99,
      stock: 140,
      tags: ['travel', 'convenience', 'practical', 'budget'],
      image: 'https://images.unsplash.com/photo-1565026057447-bc90a3dceb87',
      inStock: true,
    },
    {
      title: 'Gloves - Leather Touch Screen',
      description: 'Leather gloves with touchscreen compatibility. Warmth without compromising functionality.',
      category: 'accessories',
      price: 44.99,
      stock: 110,
      tags: ['winter', 'leather', 'tech', 'premium', 'practical'],
      image: 'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9',
      inStock: true,
    },
    {
      title: 'Umbrella - Compact Auto',
      description: 'Automatic compact umbrella for rainy days. Portable and reliable.',
      category: 'accessories',
      price: 24.99,
      stock: 160,
      tags: ['travel', 'portable', 'convenience', 'budget', 'practical'],
      image: 'https://images.unsplash.com/photo-1511556820780-d912e42b4980',
      inStock: true,
    },
    {
      title: 'Keychain - Leather Tag',
      description: 'Personalized leather keychain. Thoughtful small gift or personal accessory.',
      category: 'accessories',
      price: 14.99,
      stock: 300,
      tags: ['gift', 'leather', 'budget', 'personalized', 'daily-use'],
      image: 'https://images.unsplash.com/photo-1582454780421-aca5c3ef5742',
      inStock: true,
    },
  ];

  // ============================================
  // HOME & DAILY ESSENTIALS (10 products)
  // ============================================
  const homeEssentials = [
    {
      title: 'Stainless Steel Water Bottle',
      description: 'Insulated water bottle keeps drinks cold for 24 hours. Eco-friendly and durable.',
      category: 'home',
      price: 29.99,
      stock: 200,
      tags: ['eco', 'daily-use', 'health', 'portable', 'budget'],
      image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8',
      inStock: true,
    },
    {
      title: 'Coffee Maker - Programmable',
      description: 'Programmable coffee maker for morning convenience. Wake up to fresh coffee.',
      category: 'home',
      price: 79.99,
      stock: 110,
      tags: ['daily-use', 'convenience', 'home', 'coffee'],
      image: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6',
      inStock: true,
    },
    {
      title: 'Bed Sheet Set - Cotton',
      description: 'Soft cotton bed sheet set for comfortable sleep. Breathable and cozy.',
      category: 'home',
      price: 59.99,
      stock: 130,
      tags: ['comfort', 'home', 'daily-use', 'quality'],
      image: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace',
      inStock: true,
    },
    {
      title: 'Meal Prep Containers - Set of 10',
      description: 'BPA-free meal prep containers for healthy eating. Microwave and dishwasher safe.',
      category: 'home',
      price: 24.99,
      stock: 180,
      tags: ['health', 'convenience', 'budget', 'daily-use', 'practical'],
      image: 'https://images.unsplash.com/photo-1606656062412-9f718484f049',
      inStock: true,
    },
    {
      title: 'Throw Blanket - Fleece',
      description: 'Cozy fleece throw blanket for couch and bed. Soft and warm.',
      category: 'home',
      price: 34.99,
      stock: 150,
      tags: ['comfort', 'cozy', 'home', 'gift'],
      image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2',
      inStock: true,
    },
    {
      title: 'Desk Organizer - Wood',
      description: 'Wooden desk organizer for office supplies. Keep your workspace tidy.',
      category: 'home',
      price: 39.99,
      stock: 120,
      tags: ['office', 'organization', 'home', 'productivity'],
      image: 'https://images.unsplash.com/photo-1577017040065-650ee4d43339',
      inStock: true,
    },
    {
      title: 'Essential Oil Diffuser',
      description: 'Ultrasonic essential oil diffuser for aromatherapy. Create a relaxing atmosphere.',
      category: 'home',
      price: 44.99,
      stock: 140,
      tags: ['home', 'relaxation', 'mood', 'gift', 'wellness'],
      image: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2',
      inStock: true,
    },
    {
      title: 'Bath Towel Set - Luxury',
      description: 'Plush luxury bath towels for spa-like experience. Soft and absorbent.',
      category: 'home',
      price: 49.99,
      stock: 100,
      tags: ['luxury', 'comfort', 'home', 'quality', 'gift'],
      image: 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2',
      inStock: true,
    },
    {
      title: 'Kitchen Knife Set - Professional',
      description: 'Professional kitchen knife set with block. Essential for home cooking.',
      category: 'home',
      price: 129.99,
      stock: 70,
      tags: ['home', 'cooking', 'quality', 'professional', 'gift'],
      image: 'https://images.unsplash.com/photo-1593618998160-e34014e67546',
      inStock: true,
    },
    {
      title: 'Plant Pot Set - Ceramic',
      description: 'Beautiful ceramic plant pots for indoor plants. Add greenery to your home.',
      category: 'home',
      price: 34.99,
      stock: 160,
      tags: ['home', 'decor', 'gift', 'aesthetic'],
      image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411',
      inStock: true,
    },
  ];

  // Combine all products
  const allProducts: Array<any> = [
    ...mensClothing,
    ...womensClothing,
    ...footwear,
    ...electronics,
    ...laptops,
    ...accessories,
    ...homeEssentials,
  ];

  console.log('📊 Product breakdown:');
  console.log(`   - Men's Clothing: ${mensClothing.length}`);
  console.log(`   - Women's Clothing: ${womensClothing.length}`);
  console.log(`   - Footwear: ${footwear.length}`);
  console.log(`   - Electronics: ${electronics.length}`);
  console.log(`   - Laptops: ${laptops.length}`);
  console.log(`   - Accessories: ${accessories.length}`);
  console.log(`   - Home Essentials: ${homeEssentials.length}`);
  console.log(`   - TOTAL: ${allProducts.length} products\n`);

  // Insert all products
  let count = 0;
  for (const product of allProducts) {
    await prisma.product.create({
      data: {
        ...product,
        vendorId: product.vendorId ?? vendor.id,
      },
    });
    count++;
    if (count % 10 === 0) {
      console.log(`✅ Created ${count}/${allProducts.length} products`);
    }
  }

  console.log('\n✅ Database seeded successfully!');
  console.log(`📦 Total products created: ${allProducts.length}`);

  // Count unique tags
  const allTags = new Set<string>();
  allProducts.forEach((p) => p.tags.forEach((tag) => allTags.add(tag)));
  console.log(`🏷️  Unique tags: ${allTags.size}`);
  console.log(`🏷️  Tags: ${Array.from(allTags).sort().join(', ')}\n`);

  // Price range
  const prices = allProducts.map((p) => p.price);
  console.log(`💰 Price range: $${Math.min(...prices)} - $${Math.max(...prices)}`);
  console.log(`💰 Average price: $${(prices.reduce((a, b) => a + b, 0) / prices.length).toFixed(2)}\n`);
}

main()
  .catch((e) => {
    console.error('❌ Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
